name = "workers-cloudflare-com"
account_id = "8995c0f49cdcf57eb54d2c1e52b7d2f3"
main = "./index.js"
compatibility_date = "2022-12-14"
workers_dev = true
kv_namespaces = [
  { binding = "BUILT_WITH_WORKERS", id = "b2817b8f747d4f1b9bf87712eb72d1b5" } # prod
]

[env.production]
workers_dev = false
route = "https://workers.cloudflare.com/*"
kv_namespaces = [
  { binding = "BUILT_WITH_WORKERS", id = "b2817b8f747d4f1b9bf87712eb72d1b5" } # prod
]
