on:
  push:
    branches:
      - master
  repository_dispatch:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
    - uses: actions/checkout@master
    - name: "Trigger Pages deploy"
      run: |
        curl "https://api.github.com/repos/$REPO/dispatches" \
         -X POST \
         -H "Accept: application/vnd.github.v3+json" \
         -H "Authorization: token $GITHUB_TOKEN" \
         -d "{\"event_type\":\"Repository Dispatch\", \"client_payload\": { \"project_name\": \"$PROJECT_NAME\" }}"
      env:
        REPO: ${{ secrets.PAGES_REPO }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PROJECT_NAME: ${{ secrets.PAGES_PROJECT_NAME }}
    - name: Publish app
      uses: cloudflare/wrangler-action@master
      with:
        apiToken: ${{ secrets.apiKey }}
        environment: "production"
        workingDirectory: "worker"
